import type { Metadata } from "next";
import "./globals.css";
import { useEffect } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>
type Page = {
  id:number;
  title:string;
  body:string;
}
export default async function RootLayout({
  children,
}: RootLayoutProps) {
  const resp = await fetch('http://localhost:9999/pages');
  const data:Page[] = await resp.json();
  const liTags = data.map((item)=>{
    return <li key={item.id}><a href={`/read/${item.id}`}>{item.title}</a></li>
  });
  console.log('liTags', liTags);
  return (
    <html lang="en">
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          {liTags}
        </ol>
        {children}
        <ul>
          <li><a href="/create">Create</a></li>
          <li><a href="/update/id">Update</a></li>
          <li><button>Delete</button></li>
        </ul>
      </body>
    </html>
  );
}
